version: '3'
services:
  app:
    container_name: friend_management
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports: 
      - 8081:8081
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mydb
    networks:
      - backend

  mydb:
    image: mysql:5.6
    container_name: db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - database_mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge